version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-simple
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - redis-network

  data-loader:
    build: .
    container_name: data-loader-simple
    depends_on:
      - redis
    volumes:
      - .:/app
    command: python3 load_data_simple.py
    networks:
      - redis-network

volumes:
  redis-data:

networks:
  redis-network:
    driver: bridge 